In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [60]:
combined_df=pd.DataFrame(columns = ["area","st","year", "occ_title","occ_group","tot_emp","h_median"])
file_list=[]
file_suffix=""
file_structure=f"./state_M{file_suffix}"
for x in range(2002, 2019):
    if x <2014 :
        file_suffix=f"{x}_dl.xls"
    else:
        file_suffix=f"{x}_dl.xlsx"        
    temp_df=pd.read_excel(file_structure+file_suffix)
    temp_df.columns = [y.lower() for y in temp_df.columns]
    temp_df["year"]=x
#   The occupational group changed names in 2012 from group to occ group
#   The old ones only had major and total defined and detailed was blank also
    if x < 2012:
        temp_df["occ_group"]=temp_df["group"]
        temp_df["occ_group"].fillna('detailed',inplace=True)
    temp_df=temp_df[["area","st","year", "occ_title","occ_group","tot_emp","h_median"]]
    
#    Select only major Categories
    temp_df=temp_df.loc[temp_df["occ_group"] == "major" ]

    print(f"year = {x}")
    print(temp_df.info())
    combined_df=combined_df.append(temp_df,ignore_index=True)
    file_list.append(file_structure+file_suffix)


print(file_list)

year = 2002
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1236 entries, 0 to 32388
Data columns (total 7 columns):
area         1236 non-null int64
st           1236 non-null object
year         1236 non-null int64
occ_title    1236 non-null object
occ_group    1236 non-null object
tot_emp      1236 non-null object
h_median     1236 non-null object
dtypes: int64(2), object(5)
memory usage: 77.2+ KB
None
year = 2003
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1183 entries, 1 to 32338
Data columns (total 7 columns):
area         1183 non-null int64
st           1183 non-null object
year         1183 non-null int64
occ_title    1183 non-null object
occ_group    1183 non-null object
tot_emp      1183 non-null object
h_median     1183 non-null object
dtypes: int64(2), object(5)
memory usage: 73.9+ KB
None
year = 2004
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1184 entries, 1 to 35843
Data columns (total 7 columns):
area         1184 non-null int64
st           1184 non-null object
year         1184 non-null int64
occ_title    1184 non-null object
occ_group    1184 non-null object
tot_emp      1184 non-null object
h_median     1184 non-null object
dtypes: int64(2), object(5)
memory usage: 74.0+ KB
None
year = 2005
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1181 entries, 1 to 36222
Data columns (total 7 columns):
area         1181 non-null int64
st           1181 non-null object
year         1181 non-null int64
occ_title    1181 non-null object
occ_group    1181 non-null object
tot_emp      1181 non-null object
h_median     1181 non-null object
dtypes: int64(2), object(5)
memory usage: 73.8+ KB
None
year = 2006
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1184 entries, 1 to 35780
Data columns (total 7 columns):
area         1184 non-null int64
st           1184 non-null object
year         1184 non-null int64
occ_title    1184 non-null object
occ_group    1184 non-null object
tot_emp      1184 non-null object
h_median     1184 non-null object
dtypes: int64(2), object(5)
memory usage: 74.0+ KB
None
year = 2007
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1186 entries, 1 to 36805
Data columns (total 7 columns):
area         1186 non-null int64
st           1186 non-null object
year         1186 non-null int64
occ_title    1186 non-null object
occ_group    1186 non-null object
tot_emp      1186 non-null object
h_median     1186 non-null object
dtypes: int64(2), object(5)
memory usage: 74.1+ KB
None
year = 2008
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1185 entries, 1 to 36744
Data columns (total 7 columns):
area         1185 non-null int64
st           1185 non-null object
year         1185 non-null int64
occ_title    1185 non-null object
occ_group    1185 non-null object
tot_emp      1185 non-null object
h_median     1185 non-null object
dtypes: int64(2), object(5)
memory usage: 74.1+ KB
None
year = 2009
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1186 entries, 1 to 36712
Data columns (total 7 columns):
area         1186 non-null int64
st           1186 non-null object
year         1186 non-null int64
occ_title    1186 non-null object
occ_group    1186 non-null object
tot_emp      1186 non-null object
h_median     1186 non-null object
dtypes: int64(2), object(5)
memory usage: 74.1+ KB
None
year = 2010
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1184 entries, 1 to 36552
Data columns (total 7 columns):
area         1184 non-null int64
st           1184 non-null object
year         1184 non-null int64
occ_title    1184 non-null object
occ_group    1184 non-null object
tot_emp      1184 non-null object
h_median     1184 non-null object
dtypes: int64(2), object(5)
memory usage: 74.0+ KB
None
year = 2011
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1185 entries, 1 to 36620
Data columns (total 7 columns):
area         1185 non-null int64
st           1185 non-null object
year         1185 non-null int64
occ_title    1185 non-null object
occ_group    1185 non-null object
tot_emp      1185 non-null object
h_median     1185 non-null object
dtypes: int64(2), object(5)
memory usage: 74.1+ KB
None
year = 2012
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1184 entries, 1 to 37621
Data columns (total 7 columns):
area         1184 non-null int64
st           1184 non-null object
year         1184 non-null int64
occ_title    1184 non-null object
occ_group    1184 non-null object
tot_emp      1184 non-null object
h_median     1184 non-null object
dtypes: int64(2), object(5)
memory usage: 74.0+ KB
None
year = 2013
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1187 entries, 1 to 37711
Data columns (total 7 columns):
area         1187 non-null int64
st           1187 non-null object
year         1187 non-null int64
occ_title    1187 non-null object
occ_group    1187 non-null object
tot_emp      1187 non-null object
h_median     1187 non-null object
dtypes: int64(2), object(5)
memory usage: 74.2+ KB
None
year = 2014
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1188 entries, 1 to 37701
Data columns (total 7 columns):
area         1188 non-null int64
st           1188 non-null object
year         1188 non-null int64
occ_title    1188 non-null object
occ_group    1188 non-null object
tot_emp      1188 non-null object
h_median     1188 non-null object
dtypes: int64(2), object(5)
memory usage: 74.2+ KB
None
year = 2015
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1188 entries, 1 to 37626
Data columns (total 7 columns):
area         1188 non-null int64
st           1188 non-null object
year         1188 non-null int64
occ_title    1188 non-null object
occ_group    1188 non-null object
tot_emp      1188 non-null object
h_median     1188 non-null object
dtypes: int64(2), object(5)
memory usage: 74.2+ KB
None
year = 2016
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1188 entries, 1 to 37548
Data columns (total 7 columns):
area         1188 non-null int64
st           1188 non-null object
year         1188 non-null int64
occ_title    1188 non-null object
occ_group    1188 non-null object
tot_emp      1188 non-null object
h_median     1188 non-null object
dtypes: int64(2), object(5)
memory usage: 74.2+ KB
None
year = 2017
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1188 entries, 1 to 36978
Data columns (total 7 columns):
area         1188 non-null int64
st           1188 non-null object
year         1188 non-null int64
occ_title    1188 non-null object
occ_group    1188 non-null object
tot_emp      1188 non-null object
h_median     1188 non-null object
dtypes: int64(2), object(5)
memory usage: 74.2+ KB
None
year = 2018
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1187 entries, 1 to 36884
Data columns (total 7 columns):
area         1187 non-null int64
st           1187 non-null object
year         1187 non-null int64
occ_title    1187 non-null object
occ_group    1187 non-null object
tot_emp      1187 non-null object
h_median     1187 non-null object
dtypes: int64(2), object(5)
memory usage: 74.2+ KB
None
['./state_M2002_dl.xls', './state_M2003_dl.xls', './state_M2004_dl.xls', './state_M2005_dl.xls', './state_M2006_dl.xls', './state_M2007_dl.xls', './state_M2008_dl.xls', './state_M2009_dl.xls', './state_M2010_dl.xls', './state_M2011_dl.xls', './state_M2012_dl.xls', './state_M2013_dl.xls', './state_M2014_dl.xlsx', './state_M2015_dl.xlsx', './state_M2016_dl.xlsx', './state_M2017_dl.xlsx', './state_M2018_dl.xlsx']

In [61]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20204 entries, 0 to 20203
Data columns (total 7 columns):
area         20204 non-null object
st           20204 non-null object
year         20204 non-null object
occ_title    20204 non-null object
occ_group    20204 non-null object
tot_emp      20204 non-null object
h_median     20204 non-null object
dtypes: object(7)
memory usage: 1.1+ MB

In [12]:
con = sqlite3.connect("./alternate_data.db")
combined_df.to_sql("alternate_data", con)